### ISSUE TITLE
Final requirements of the project

### ISSUE THREAD

**Issue by BrFranceN** [airoprojects/visiope#3]
- Presentation of dataset
- Presentation of the problem -> briefly presentation of semgantation 
- List our problems
- Explain the difference between our models and the model on the paper
- Results:
 Compare: 1.Transformations, 2.Models, 3. Loss AND the original result on the paper
- Analysis of result 
         Why is good? Why is bad?
- Future developments

**Comment by airoprojects** [comment]
Finish
